sudo: false
language: ruby
rvm: 2.5.3
jdk: openjdk8
cache: bundler
jobs:
  include:
    - if: branch = master
      script:
      - NO_CONTRACTS=true bundle exec middleman build --no-clean
      after_success:
      - bundle exec s3_website push --config-dir=.s3_website-staging
    - if: branch = release
      script:
      - NO_CONTRACTS=true bundle exec middleman build --no-clean
      after_success:
      - bundle exec s3_website push --config-dir=.s3_website-release
