sudo: false
language: ruby
rvm: 2.3.4 # pre-installed
cache: bundler
jobs:
  include:
    - if: branch = master
      script:
      - bundle exec middleman build
      after_success:
      - bundle exec s3_website push --config-dir=.s3_website-staging
    - if: branch = release
      script:
      - bundle exec middleman build
      after_success:
      - bundle exec s3_website push --config-dir=.s3_website-release
