sudo: false
language: ruby
rvm: 2.3.4 # pre-installed
# branches:
#   only: release
cache: bundler
jobs:
  include:
    - script:
      - bundle exec middleman build
    - if: branch = master
      script:
      - bundle exec s3_website push --config-dir=.s3_website-stage
    - if: branch = release
      script:
      - bundle exec s3_website push --config-dir=.s3_website-release
